//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dojo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdtProjectEntities4 : DbContext
    {
        public AdtProjectEntities4()
            : base("name=AdtProjectEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<MembershipPayment> MembershipPayments { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductPayment> ProductPayments { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestPayment> TestPayments { get; set; }
    }
}
