//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.ProductPayments = new HashSet<ProductPayment>();
            this.HAS_CERTIFICATE = new HashSet<HAS_CERTIFICATE>();
            this.Parents = new HashSet<Parent>();
        }
    
        public string STUDENT_ID { get; set; }
        public string STUDENT_Fname { get; set; }
        public string STUDENT_Lname { get; set; }
        public System.DateTime STUDENT_DOB { get; set; }
        public string StreetName { get; set; }
        public string Town { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string email { get; set; }
        public System.DateTime DateJoined { get; set; }
        public string Membership_ID { get; set; }
        public bool IsActive { get; set; }
        public bool IsParent { get; set; }
        public string Rank_ID { get; set; }
        public string Parent_ID { get; set; }
        public string AttendanceCount { get; set; }
        public Nullable<System.DateTime> MembershipValidTill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Membership Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPayment> ProductPayments { get; set; }
        public virtual Rank Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAS_CERTIFICATE> HAS_CERTIFICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent> Parents { get; set; }
    }
}
